FolderName: WFDashboard
DatasourceUid: "P6693426190CB2316"
ApiToken: eyJrIjoiZUtSZVlmcHJoNFQ3Z1poQTFZd3lwbXp1V0RSejFPZ1EiLCJuIjoiQWRkUnVsZXNUb2tlbiIsImlkIjoxfQ==
GrafanaHost: https://localhost:8080/
Source: wavefront
StopOnUnsupportedQuery: false
StopOnUnsupportedChart: false
AlertURLAnnotation: "https://workday.wavefront.com/alerts/"
DecimalPrecision: 3
# AlertOutfileFormat: valid options are yam or json
AlertOutfileFormat: yaml
# AlertFormat valid options are prom/grafana/both
AlertFormat: prom
# NotificantSettings configures how the converter will look up notificant
# from the notificants.json input file. For each notificant, the lookup_value
# is looked up in the "recipient" and "response" fields in a case-insensitive, substring matching way.
# NotificantSettings together with the AlertConversionRules should help automatically add the right
# labels and annotations to each converted alert.
NotificantSettings:
  - name: bigpanda
    lookup_value: https://api.bigpanda.io/data/v2/alerts
  - name: slack
    lookup_value: https://hooks.slack.com/
  - name: pagerduty
    lookup_value: pagerduty
# AlertConversionRules specifies the rules to be applied for extracting labels and annotations
# from an alert payload. Here's how these settings are used.
# For any given alert, the alerts target id is looked up from the "input notificants file" (this is
# the response of /api/v2/notificant/ from wavefront which will give all notificants in the system).
# Recipient and method fields for that notificant is matched against the above NotificationSettings. If
# a notificant is matched then the "name" of that notificant is looked up in the following rules to find
# if there are conversion rules to be applied.
# A given alert conversion rule specifies:
#  lookup_field - which field in the alert to be looked up to find lookup_key(s) and if found,
#  then a label/annotation with out_key:<found_value> will be added to label/annotation otherwise
#  out_key:<default> is added.
# Example:
# if an alert uses id: 38kOQeCgEa33oysw in targetEndpoints or Targets[<severity>] or Target or []TargetInfo
# then converter will lookup '38kOQeCgEa33oysw' in notificants.json. The Recipient and Method fields of Notificant
# are then looked up against each of the lookup_value(s) in NotificantSettings. Let's assume that it matched
# with name: bigpanda, that means that this alert uses bigpanda target and therefore the labels and annotations
# will be applied from 'bigpanda' section below.
# Additionally, if the field 'AdditionalInformation' contains 'owner:<someval>' (note that 'owner' is one of the lookup_key)
# then wd_owner=<someval> is added to the labels.
# 'base' definition is always applied with fields overwritten from more specific targets if found.
AlertConversionRules:
  base:
    labels:
      - lookup_key: wd_owner,owner
        lookup_field: AdditionalInformation
        out_key: wd_owner
        default: <Undefined>
      - lookup_key: wd_service,service
        lookup_field: AdditionalInformation
        out_key: wd_service
        default: <Undefined>
    annotations:
      - lookup_key: description
        lookup_field: Name
        out_key: description
        default: <Undefined>
      - lookup_key: summary
        out_key: summary
        default: <Undefined>
      - lookup_key: runbook
        lookup_field: RunbookLinks,AdditionalInformation
        out_key: runbook
        default: <Undefined>
  bigpanda:  # If this key is found, then bigpanda:true is added to labels.
    labels:
      - lookup_key: wd_dc_physical
        lookup_field: AdditionalInformation
        out_key: wd_dc_physical
        default: <Undefined>
      - lookup_key: wd_env_physical
        lookup_field: AdditionalInformation
        out_key: wd_env_physical
        default: <Undefined>
      - lookup_key: wd_alert_type
        out_key: wd_alert_type
        default: <Undefined>
      - lookup_key: wd_platform
        out_key: wd_platform
        default: <Undefined>
      - lookup_key: monitoring_platform
        out_key: monitoring_platform
        default: pharos-metrics
      - lookup_key: wd_service_category
        out_key: wd_service_category
        default: <Undefined>
    annotations:
      - lookup_key: unity_link
        out_key: unity_link
        default: <Undefined>
  pagerduty:
    labels:
    annotations:
  slack:
    labels:
    annotations:
DashboardDefaults:
  TimeRange: 10m
  Span: 15m
  Color: green
  Palette: palette-classic
VariableConversions:
  host: source
MissingMetricIndicator: "*** "
FolderNameToFolderId:
  bds: 586
  csv: 599
  customer-insights: 559
  dapeng: 262
  envdata: 565
  dpm: 260
  alerts: 333
  drogon: 603
  ec: 490
  xwt: 604
  inf-api: 608
  inf-containers: 473
  inf-dns: 610
  inf-tools: 472
  infsre-net: 569
  infsre-sys: 468
  ia: 573
  kenobi: 261
  lasd: 570
  mia: 576
  mldevops_namespace: 566
  netauto: 486
  opseng: 606
  perftools: 386
  platstor: 598
  platsec: 602
  prism: 575
  ptpe: 568
  Sandbox: 631
  scylla: 609
  search-gap: 508
  search-reports: 507
  secpi: 502
  security-tools-devops: 381
  servicediscovery: 572
  stories: 622
  tco: 607
  phoenix: 571
  tlepcauto: 626
  uiplatform: 595
  drs: 596
  iplookup: 593
  microscope: 585
  sas: 594
  uiplatform-sandbox: 597
  uam: 503
  upc: 574
  vaas: 360
  wpc: 577
  zonda: 615
ParserConfig:
  NoopFuncs:
    - interpolate
    - bestEffort
    - default
    - last
  SpaceAggrVars:
    "${sum}" : "sum"
  TimeAggrVars:
  FunctionVars:
    "${interpolate}" : "interpolate"
  AdditionalMetricChars: "[]^\\/~"
  Sanitize:
    "\t" : " "
  Operators:
    "gt" : ">"
    "gte" : ">="
    "lt" : "<"
    "lte" : "<="
  RangeTranslations:
    "default" : "5m"  # Default is translated to 5m
    "vw" : "4h" # view window to time window translation - assuming 1vw = 4h here.
    "bw" : "2h" # bucket window - defaulting to 2 hours.
  UnitTranslations:
    "M" : "000000" # M is translated to six zeros (1,000,000)
  CustomTagRules:
    - Tagname: source
      Wildcard: false
      Default: TBD
      Description: "wildcard is not allowed for source tags value. Please see https://docs.google.com/document/d/16FTIiA_Zzaa1pUCAHiUcUsm6Reei35MCnJd7JYIm8tI/edit#heading=h.ehtrwmrq65x"
      # 'split' policy will split the 'source' label and values based on the following splitrules.
      Policy: split
      # Following splitrule mean that 'source' label will be split to the list of specified tagnames and for each of those tags, if the 'lookup' value is found in the original value then it is replaced with 'use' value
      Splitrules:
        - Tagname: wd_dc_physical
          Lookup: pdx
          Use: us-west-2
        - Tagname: wd_env_physical
          Lookup: eng
          Use: eng
    - Tagname: _name_
      Policy: drop # This policy will drop '_name_ tag and value from the generated query.
      Wildcard: false
      Default: TBD
      Description: "wildcard is not allowed for _name_ tag value. Please see https://docs.google.com/document/d/16FTIiA_Zzaa1pUCAHiUcUsm6Reei35MCnJd7JYIm8tI/edit#heading=h.ehtrwmrq65x"
    - Tagname: cname
      Policy: replace_with_default  # This policy will add 'cname="TBD" as label because TBD is the default value for this tag
      Wildcard: false
      Default: TBD
      Description: "wildcard is not allowed for cname tag value. Please see https://docs.google.com/document/d/16FTIiA_Zzaa1pUCAHiUcUsm6Reei35MCnJd7JYIm8tI/edit#heading=h.ehtrwmrq65x"
  AdditionalDescriptions:
    - Name: if
      Type: function
      Description: "Please check https://docs.google.com/drawings/d/1A-Uq1Rze_LU1cn7ey87VAld7h0SZ0kjjdj6jE2plPY8/edit?usp=sharing for workaround"
    - Name: orElse
      Type: function
      Description: "For orElse consider using something like https://grafana.com/docs/grafana/latest/panels-visualizations/configure-value-mappings/ in the relevant panel if it fits the need of this query."
    - Name: alert
      Type: metric_name
      Description: "'alerts' in prom should be looked up using count(ALERTS{wd_owner=“<namespace>”})) instead. Please see https://docs.google.com/drawings/d/1A-Uq1Rze_LU1cn7ey87VAld7h0SZ0kjjdj6jE2plPY8/edit?usp=sharing"
